---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: markup
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 10000
      protocol: TCP
      targetPort: 10000
  selector:
    app: markup
