---
- name: Ensure procps is installed.
  ansible.builtin.package:
    name: "{{ procps_package }}"
    state: present
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

- name: Add proper module to kernel
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter 
    
# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Let iptables see bridged traffic.
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward  
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10
