---
ansible_host: 192.168.0.132
ansible_user: vagrant
ansible_ssh_private_key_file: "./.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"

kubernetes_apiserver_advertise_address: "{{ ansible_host }}"
kubernetes_role: "control-node"