all:
  children:
    k8s_ha_control_node:
      hosts:
        control-node-[1:3]:
    k8s_workers:
      hosts:
        worker-[1:3]:
    k8s_gateways:
      hosts:
        gw-[1:2]:
    k8s_cluster:
      children:
        k8s_ha_control_node:
        k8s_workers:
        k8s_gateways:
    k8s_not_control_nodes:
      children:
        k8s_workers:
        k8s_gateways: