kustomize_dir:
  - /home/{{ ansible_host_username.stdout }}/kustomize

env: dev

dbnet_image:
  name: busybox
  tag: "1.34.0"

master_image:
  name: busybox
  tag: "1.35.0"

tesseract_image:
  name: busybox
  tag: "1.36.0"
  port: 10001
