---
application_namespace: application
gitlab_regisry_address: https://192.168.0.1
gitlab_regisry_user: deploy

kustomize_dir:
  - /home/{{ ansible_host_username.stdout }}/kustomize

env: dev

dbnet_image:
  name: nginx
  tag: "1.23.3"

master_image:
  name: nginx
  tag: "1.23"

tesseract_image:
  name: nginx
  tag: "1.22.1"
  port: 10001
