---
kustomize_dir:
  - /home/{{ ansible_host_username.stdout }}/kustomize

env: dev

dbnet_image:
  name: nginx
  tag: "1.23.3"

master_image:
  name: nginx
  tag: "1.23"

tesseract_image:
  name: nginx
  tag: "1.22.1"
  port: 10001
